### ISSUE TITLE
额 大神 我用了您的控件 出现了一个问题

### ISSUE THREAD

**Issue by sq9523** [llxdaxia/MultiView#5]
就是使用点击弹出的那个Activity 报了The specified child already has a parent. You must call removeView() on the child's parent first. 这个异常 您需要代码环境吗

**Comment by zhazhaxin** [comment]
把异常详细信息贴出来下

**Comment by sq9523** [comment]
我把您的控件库 作为Moudle引入了 解决上面那个问题 但是在滑动新的页面后的照片却不显示了

**Comment by sq9523** [comment]
不好意思 我现在没办法给您带来得明天

**Comment by zhazhaxin** [comment]
OK

**Comment by sq9523** [comment]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                  at android.view.ViewGroup.addViewInner(ViewGroup.java:3430)
                                                                  at android.view.ViewGroup.addView(ViewGroup.java:3301)
                                                                  at android.support.v4.view.ViewPager.addView(ViewPager.java:1505)
                                                                  at android.view.ViewGroup.addView(ViewGroup.java:3246)
                                                                  at android.view.ViewGroup.addView(ViewGroup.java:3222)
                                                                  at cn.lemon.multi.ui.ViewImageAdapter.instantiateItem(ViewImageAdapter.java:43)
                                                                  at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1034)
                                                                  at android.support.v4.view.ViewPager.populate(ViewPager.java:1216)
                                                                  at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                  at android.support.v4.view.ViewPager$3.run(ViewPager.java:273)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:579)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:547)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
                                                                  at android.os.Handler.handleCallback(Handler.java:725)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                  at android.os.Looper.loop(Looper.java:153)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5293)
                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:511)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by sq9523** [comment]
不知道为什么在您内置的activity里 切换照片便会出现这个问题

**Comment by sq9523** [comment]
一旦在 image = createImage(key);之前加入container.removeView(image);会解决这个问题 但是所有的照片都会没有显示
