### ISSUE TITLE
你好呀    我使用这个库滑动预览图片时   总共29张图片到27的时候出现这个异常是怎么回事呢

### ISSUE THREAD

**Issue by kris-liutao** [llxdaxia/MultiView#6]
12004-12004/com.zontonec.ztkid E/InputEventReceiver: Exception dispatching input event.
03-09 10:40:08.126 12004-12004/com.zontonec.ztkid E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
03-09 10:40:08.128 12004-12004/com.zontonec.ztkid E/MessageQueue-JNI: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                          at android.view.ViewGroup.addViewInner(ViewGroup.java:4471)
                                                                          at android.view.ViewGroup.addView(ViewGroup.java:4312)
                                                                          at android.support.v4.view.ViewPager.addView(ViewPager.java:1477)
                                                                          at android.view.ViewGroup.addView(ViewGroup.java:4252)
                                                                          at android.view.ViewGroup.addView(ViewGroup.java:4225)
                                                                          at com.zontonec.ztkid.rongcloude.nineimage.ui.ViewImageAdapter.instantiateItem(ViewImageAdapter.java:52)
                                                                          at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1002)
                                                                          at android.support.v4.view.ViewPager.populate(ViewPager.java:1216)
                                                                          at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
                                                                          at android.support.v4.view.ViewPager$3.run(ViewPager.java:267)
                                                                          at android.support.v4.view.ViewPager.completeScroll(ViewPager.java:1997)
                                                                          at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2127)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2212)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                                          at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
                                                                          at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
                                                                          at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
                                                                          at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                          at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
                                                                          at android.view.View.dispatchPointerEvent(View.java:10233)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4856)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4717)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4395)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4452)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
                                                                          at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6681)
                                                                          at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6655)
                                                                          at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6616)
                                                                          at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6808)
                                                                          at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
                                                                          at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                          at android.os.MessageQueue.next(MessageQueue.java:359)
                                                                          at android.os.Looper.loop(Looper.java:138)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6585)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                      	
03-09 10:40:08.183 12004-12162/com.

@xinzhazha

**Comment by kris-liutao** [comment]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                          at android.view.ViewGroup.addViewInner(ViewGroup.java:4471)
                                                                          at android.view.ViewGroup.addView(ViewGroup.java:4312)
                                                                          at android.support.v4.view.ViewPager.addView(ViewPager.java:1477)
                                                                          at android.view.ViewGroup.addView(ViewGroup.java:4252)
                                                                          at android.view.ViewGroup.addView(ViewGroup.java:4225)
                                                                          at com.zontonec.ztkid.rongcloude.nineimage.ui.ViewImageAdapter.instantiateItem(ViewImageAdapter.java:52)
                                                                          at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1002)
                                                                          at android.support.v4.view.ViewPager.populate(ViewPager.java:1216)
                                                                          at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
                                                                          at android.support.v4.view.ViewPager$3.run(ViewPager.java:267)
                                                                          at android.support.v4.view.ViewPager.completeScroll(ViewPager.java:1997)
                                                                          at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2127)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2212)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                                          at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                          at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                                                                          at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
                                                                          at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
                                                                          at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
                                                                          at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                          at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
                                                                          at android.view.View.dispatchPointerEvent(View.java:10233)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4856)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4717)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4395)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4452)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
                                                                          at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6681)
                                                                          at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6655)
                                                                          at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6616)
                                                                          at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6808)
                                                                          at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
                                                                          at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                          at android.os.MessageQueue.next(MessageQueue.java:359)
                                                                          at android.os.Looper.loop(Looper.java:138)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6585)
                                                                          at java.lang.reflect.Method.invoke(Native Method)

**Comment by zhazhaxin** [comment]
更新版本到>=1.0.1

**Comment by kris-liutao** [comment]
我是没有用gradle添加依赖的形式使用的，我使用了你的model依赖的，应该就是最新版本吧 @xinzhazha

**Comment by zhazhaxin** [comment]
那你更新下代码吧。

**Comment by kris-liutao** [comment]
![b990f435-891f-4633-83f9-94ccda621ef0](https://user-images.githubusercontent.com/24263746/37240323-bc7ced14-2484-11e8-992d-6332795670a0.png)
@xinzhazha 


我MultiView将代码更新了但是还是提示ViewImageAdapter下面的方法不太对呢

   @Override
    public Object instantiateItem(ViewGroup container, int position) {

        String key = mImageUrls.get(position);
        HttpImageView image;

        if(mCacheImages.containsKey(key)){
            image = mCacheImages.get(key).get();
            if (image == null){
                image = createImage(key);
            }
        } else {
            image = createImage(key);
        }

        container.addView(image);

        return image;
    }

**Comment by zhazhaxin** [comment]
sorry，之前没注意到这里。你重新更新下代码。

**Comment by kris-liutao** [comment]
好的  谢谢了 @xinzhazha
